# 公共配置文件
spring:
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.138.185.20:3306/sr_init_base
    username: sr_init_base
    password: YGABPsxFPzX5fkwd

  # Redis 配置
  redis:
    database: 1
    host: localhost
    port: 6379
    timeout: 5000
#    password: 123456

  # Elasticsearch 配置
  # todo 需替换配置，然后取消注释
#  elasticsearch:
#    uris: http://localhost:9200
#    username: root
#    password: 123456
